POST http://localhost:8000/api/token/
Content-Type: application/json

{
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyOTc3NzYxLCJpYXQiOjE3NTI5Nzc3MDEsImp0aSI6ImY1ZWI5NjY3NjIyMTQxZWE5MmEyMGRhM2YzNGMwMzU5IiwidXNlcl9pZCI6MX0.B2ykA8968YgvjqwFE6Wm0WBU_ZUaYmLYcul4tparI_Y"
  "password": "admin"
}

###

POST http://127.0.0.1:8000/api/v1/dogs/
Content-Type: application/json

 {
    "name": "Teste 2",
    "age": 1,
    "gender": "Male",
    "description": "Teste 2",
    "price": "1000.00",
    "breed": 2
  }


###


POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}
