# Generated by Django 5.2.1 on 2025-08-26 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('PROCESSING', 'Em Processamento'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregue'), ('CANCELLED', 'Cancelado'), ('RETURNED', 'Devolvido')], default='PENDING', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='address.address')),
                ('user_buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_buyer', to=settings.AUTH_USER_MODEL)),
                ('user_seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço da compra')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='order.order')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.pet')),
            ],
        ),
    ]
